MongeTestCatalogs/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongeTestCatalogs.Data;

namespace MongeTestCatalogs.Controllers
{
    [Route("[controller]/[action]")]
    public class AccountController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;

        public AccountController(SignInManager<ApplicationUser> signInManager, ILogger<AccountController> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToPage("/Index");
        }
    }
}

MongeTestCatalogs/Controllers/FaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace MongeTestCatalogs.Controllers
{
    public class FaceController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;

        public FaceController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Capture")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Capture(string base64String)
        {

            //if (!string.IsNullOrEmpty(base64String))
            //{
            //    var imageParts = base64String.Split(',').ToList<string>();
            //    byte[] imageBytes = Convert.FromBase64String(imageParts[1]);
            //    DateTime nm = DateTime.Now;
            //    string date = nm.ToString("yyyymmddMMss");

            //    string webRootPath = _hostingEnvironment.WebRootPath;
            //    string path = Path.Combine(webRootPath, "CapturedPhotos");
            //    path = Path.Combine(path, date + "CamCapture.jpg");

            //    var response = await MakeAnalysisRequest(imageBytes);

            //    System.IO.File.WriteAllBytes(path, imageBytes);
            //    return new JsonResult("'data': "+ response);
            //}
            //else
            //{
            //    return new JsonResult("'data': false");
            //}
            return new JsonResult("'data': false");
        }

        public static async Task<string> MakeAnalysisRequest(byte[] imageBytes)
        {
            const string subscriptionKey = "6b0875bdb8214351ba461904de13a39d";
            const string uriBase = "https://westcentralus.api.cognitive.microsoft.com/face/v1.0/detect";

            HttpClient client = new HttpClient();

            // Request headers.  
            client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", subscriptionKey);

            // Request parameters. A third optional parameter is "details".  
            string requestParameters = "returnFaceId=true&returnFaceLandmarks=false&returnFaceAttributes=age,gender,headPose,smile,facialHair,glasses,emotion,hair,makeup,occlusion,accessories,blur,exposure,noise";

            // Assemble the URI for the REST API Call.  
            string uri = uriBase + "?" + requestParameters;

            HttpResponseMessage response;

            // Request body. Posts a locally stored JPEG image.  
            byte[] byteData = imageBytes;

            using (ByteArrayContent content = new ByteArrayContent(byteData))
            {
                // This example uses content type "application/octet-stream".  
                // The other content types you can use are "application/json" and "multipart/form-data".  
                content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");

                // Execute the REST API call.  
                response = await client.PostAsync(uri, content);

                // Get the JSON response.  
                string contentString = await response.Content.ReadAsStringAsync();

                // Display the JSON response.  

                return JsonPrettyPrint(contentString);

            }
        }

        static string JsonPrettyPrint(string json)
        {
            if (string.IsNullOrEmpty(json))
                return string.Empty;

            json = json.Replace(Environment.NewLine, "").Replace("\t", "");

            StringBuilder sb = new StringBuilder();
            bool quote = false;
            bool ignore = false;
            int offset = 0;
            int indentLength = 3;

            foreach (char ch in json)
            {
                switch (ch)
                {
                    case '"':
                        if (!ignore) quote = !quote;
                        break;
                    case '\'':
                        if (quote) ignore = !ignore;
                        break;
                }

                if (quote)
                    sb.Append(ch);
                else
                {
                    switch (ch)
                    {
                        case '{':
                        case '[':
                            sb.Append(ch);
                            sb.Append(Environment.NewLine);
                            sb.Append(new string(' ', ++offset * indentLength));
                            break;
                        case '}':
                        case ']':
                            sb.Append(Environment.NewLine);
                            sb.Append(new string(' ', --offset * indentLength));
                            sb.Append(ch);
                            break;
                        case ',':
                            sb.Append(ch);
                            sb.Append(Environment.NewLine);
                            sb.Append(new string(' ', offset * indentLength));
                            break;
                        case ':':
                            sb.Append(ch);
                            sb.Append(' ');
                            break;
                        default:
                            if (ch != ' ') sb.Append(ch);
                            break;
                    }
                }
            }

            return sb.ToString().Trim();
        }
    }
}

MongeTestCatalogs/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MongeTestCatalogs.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MongeTestCatalogs/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MongeTestCatalogs.Data;

namespace MongeTestCatalogs.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            if (!result.Succeeded)
            {
                throw new ApplicationException($"Error confirming email for user with ID '{userId}':");
            }

            return Page();
        }
    }
}

MongeTestCatalogs/Pages/Account/ExternalLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using MongeTestCatalogs.Data;

namespace MongeTestCatalogs.Pages.Account
{
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            ILogger<ExternalLoginModel> logger)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string LoginProvider { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return RedirectToPage("./Login");
        }

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToPage("./Login");
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToPage("./Login");
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor : true);
            if (result.Succeeded)
            {
                _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(Url.GetLocalUrl(returnUrl));
            }
            if (result.IsLockedOut)
            {
                return RedirectToPage("./Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ReturnUrl = returnUrl;
                LoginProvider = info.LoginProvider;
                if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                {
                    Input = new InputModel
                    {
                        Email = info.Principal.FindFirstValue(ClaimTypes.Email)
                    };
                }
                return Page();
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                // Get the information about the user from the external login provider
                var info = await _signInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    throw new ApplicationException("Error loading external login information during confirmation.");
                }
                var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);
                        return LocalRedirect(Url.GetLocalUrl(returnUrl));
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            ReturnUrl = returnUrl;
            return Page();
        }
    }
}

MongeTestCatalogs/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MongeTestCatalogs.Data;
using MongeTestCatalogs.Services;

namespace MongeTestCatalogs.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.ResetPasswordCallbackLink(user.Id, code, Request.Scheme);
                await _emailSender.SendResetPasswordAsync(Input.Email, callbackUrl);
                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

MongeTestCatalogs/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MongeTestCatalogs.Pages.Account
{
    public class ForgotPasswordConfirmation : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MongeTestCatalogs/Pages/Account/Lockout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MongeTestCatalogs.Pages.Account
{
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MongeTestCatalogs/Pages/Account/ResetPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MongeTestCatalogs.Pages.Account
{
    public class ResetPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MongeTestCatalogs/Pages/Account/SignedOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

public class SignedOutModel : PageModel
{
    public IActionResult OnGet()
    {
        if (User.Identity.IsAuthenticated)
        {
            // Redirect to home page if the user is authenticated.
            return RedirectToPage("/Index");
        }

        return Page();
    }
}

MongeTestCatalogs/Pages/Account/AccessDenied.cshtml
@page
@model AccessDeniedModel
@{
    ViewData["Title"] = "Access denied";
}

<header>
    <h1 class="text-danger">@ViewData["Title"]</h1>
    <p class="text-danger">You do not have access to this resource.</p>
</header>

MongeTestCatalogs/Pages/Account/ConfirmEmail.cshtml
@page
@model ConfirmEmailModel
@{
    ViewData["Title"] = "Confirm email";
}

<h2>@ViewData["Title"]</h2>
<div>
    <p>
        Thank you for confirming your email.
    </p>
</div>

MongeTestCatalogs/Pages/Account/ExternalLogin.cshtml
@page
@model ExternalLoginModel
@{
    ViewData["Title"] = "Register";
}

<h2>@ViewData["Title"]</h2>
<h4>Associate your @Model.LoginProvider account.</h4>
<hr />

<p class="text-info">
    You've successfully authenticated with <strong>@Model.LoginProvider</strong>.
    Please enter an email address for this site below and click the Register button to finish
    logging in.
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="Confirmation" asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-default">Register</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

MongeTestCatalogs/Pages/Account/ForgotPasswordConfirmation.cshtml
@page
@model ForgotPasswordConfirmation
@{
    ViewData["Title"] = "Forgot password confirmation";
}

<h2>@ViewData["Title"]</h2>
<p>
    Please check your email to reset your password.
</p>

MongeTestCatalogs/Pages/Account/Login.cshtml
@page
@model LoginModel

@{
	ViewData["Title"] = "Log in";
}

<h2>@ViewData["Title"]</h2>
<div class="row">
	<div class="col-md-4">
		<section>
			<form method="post">
				<h4>Use a local account to log in.</h4>
				<hr />
				<div asp-validation-summary="All" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Input.Email"></label>
					<input asp-for="Input.Email" class="form-control" id="email_input"  />
					<span asp-validation-for="Input.Email" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Input.Password"></label>
					<input asp-for="Input.Password" class="form-control" id="password_input" />
					<span asp-validation-for="Input.Password" class="text-danger" ></span>
				</div>
				<div class="form-group">
					<div class="checkbox">
						<label asp-for="Input.RememberMe">
							<input asp-for="Input.RememberMe"  />
							@Html.DisplayNameFor(m => m.Input.RememberMe)
						</label>
					</div>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-default" id="submit_btn">Log in</button>
				</div>
				<div class="form-group">
					<p>
						<a asp-page="./ForgotPassword">Forgot your password?</a>
					</p>
					<p>
						<a asp-page="./Register" asp-route-returnUrl="@Model.ReturnUrl">Register as a new user</a>
					</p>
				</div>
			</form>
		</section>
		<div class="controls" style="font-size:25px;">
			<div class="row">
				<div class="col-md-6">
					<button style=" width: 100%; " id="take-photo" class="btn btn-default">Capture</button>
					<br />
					<button style=" width: 100%; " id="delete-photo" class="btn btn-default">Delete</button>
					<br />
					<div style="font-size:1.5em; color:Tomato">
						<a href="#" id="download-photo" download="selfie.png" title="Save Photo"
						   class="disabled">
							<i class="fas fa-download fa-sm btn btn-default">
								Download
							</i>
						</a>
					</div>
				</div>
				<div class="col-md-6">
					<a style=" width: 100%; " class="btn btn-primary visible" href="#" id="start-camera">Restart Video.</a>
					<br />
					<button style=" width: 100%; " class="btn btn-primary" onclick="CaptureAndDetect(true, detectFaces, IdentifyFace  )"> Identify Face </button>
				</div>
			</div>
			<p id="error-message"></p>
			<h4 style="color: red;" id="error_result"></h4>
		</div>
		<textarea id="responseTextArea" class="UIInput" style="width:100%; height:400px;"></textarea>
	</div>
	<div class="col-md-6">
		<h4 style="color: blue;" id="text_results">  </h4>
		<video id="camera-stream"></video>
		<canvas width="300" height="400"></canvas>
		<img id="snap" />
	</div>
</div>

<script>
	var video,
		image,
		start_camera,
		controls,
		take_photo_btn,
		delete_photo_btn,
		download_photo_btn,
		error_message,
		hidden_canvas,
		error_result,
		snap;
	var subscriptionKey = "{FACE API SUBSCRIPTION KEY}";

	window.onload = function () {
		// References to all the element we will need.
		video = document.querySelector('#camera-stream');
		image = document.querySelector('#snap');
		start_camera = document.querySelector('#start-camera');
		controls = document.querySelector('.controls');
		take_photo_btn = document.querySelector('#take-photo');
		delete_photo_btn = document.querySelector('#delete-photo');
		download_photo_btn = document.querySelector('#download-photo');
		error_message = document.querySelector('#error-message');
		hidden_canvas = document.querySelector('canvas');
		error_result = document.querySelector('#error_result');
		snap = document.querySelector('#snap');
		hidden_canvas.className = 'hidden';
		// The getUserMedia interface is used for handling camera input.
		// Some browsers need a prefix so here we're covering all the options
		navigator.getMedia = (navigator.getUserMedia ||
			navigator.webkitGetUserMedia ||
			navigator.mozGetUserMedia ||
			navigator.msGetUserMedia);
		if (!navigator.getMedia) {
			displayErrorMessage("Your browser doesn't have support for the navigator.getUserMedia interface.");
		}
		else {
			// Request the camera.
			navigator.getMedia(
				{
					video: { width: 1280, height: 720 }
				},
				// Success Callback
				function (stream) {
					// Create an object URL for the video stream and
					// set it as src of our HTLM video element.
					video.src = window.URL.createObjectURL(stream);
					// Play the video element to start the stream.
					video.play();
					video.onplay = function () {
						showVideo();
					};
				},
				// Error Callback
				function (err) {
					displayErrorMessage("There was an error with accessing the camera stream: " + err.name, err);
				}
			);

		}
		// Mobile browsers cannot play video without user input,
		// so here we're using a button to start it manually.
		start_camera.addEventListener("click", function (e) {
			hidden_canvas.className = 'hidden';
			snap.className = 'hidden';
			video.className = '';
			e.preventDefault();

			// Start video playback manually.
			video.play();
			showVideo();

		});
		take_photo_btn.addEventListener("click", function (e) {

			e.preventDefault();

			var snap = CaptureAndDetect(false);

			// Show image.
			//image.setAttribute('src', snap);
			//image.classList.add("visible");

			// Enable delete and save buttons
			delete_photo_btn.classList.remove("disabled");
			download_photo_btn.classList.remove("disabled");

			// Set the href attribute of the download button to the snap url.
			download_photo_btn.href = snap;

			// Pause video playback of stream.
			video.pause();

		});
		delete_photo_btn.addEventListener("click", function (e) {

			e.preventDefault();

			// Hide image.
			image.setAttribute('src', "");
			image.classList.remove("visible");

			// Disable delete and save buttons
			delete_photo_btn.classList.add("disabled");
			download_photo_btn.classList.add("disabled");

			// Resume playback of stream.
			video.play();

		});
	}
	function showVideo() {
		// Display the video stream and the controls.

		hideUI();
		video.classList.add("visible");
		controls.classList.add("visible");
	}
	function Uploadsubmit(datacaptured) { console.log("calling ", '@Url.Action("Capture", "Face")');  }
	function displayErrorMessage(error_msg, error) {
		error = error || "";
		if (error) {
			console.error(error);
		}
		error_message.innerText = error_msg;

		hideUI();
		error_message.classList.add("visible");
	}
	function hideUI() {
		// Helper function for clearing the app UI.
		//controls.classList.remove("visible");
		start_camera.classList.remove("visible");
		video.classList.remove("visible");
		snap.classList.remove("visible");
		error_message.classList.remove("visible");
	};
	function CaptureAndDetect(wantToDetect, execFunction, detectFunction ) {
		var video = document.querySelector('#camera-stream'),
			hidden_canvas = document.querySelector('canvas'),
			context = hidden_canvas.getContext('2d'),
			width = video.videoWidth,
			height = video.videoHeight;

		hidden_canvas.className = 'hidden';
		snap.className = '';
		video.className = 'hidden';

		if (width && height) {
			// Setup a canvas with the same dimensions as the video.
			hidden_canvas.width = width;
			hidden_canvas.height = height;
			// Make a copy of the current frame in the video on the canvas.
			context.drawImage(video, 0, 0, width, height)
			// Storing Base64String
			data = hidden_canvas.toDataURL('image/jpeg');
			if (wantToDetect) {
				//detectFaces(data);
				//addPersonFace(data);
				execFunction(data, detectFunction);
			}
			$("#snap").attr('src', data);
		}
	}
	function detectFaces(data, detectFunction ) {
		if (data) {
			fetch(data)
				.then(res => res.blob())
				.then(blobData => {
					$.post({
						url: "https://southcentralus.api.cognitive.microsoft.com/face/v1.0/detect?returnFaceId=true&returnFaceLandmarks=false",
						contentType: "application/octet-stream",
						headers: {
							'Ocp-Apim-Subscription-Key': subscriptionKey
						},
						processData: false,
						//data: blobData
						data: blobData
					})
					.done(function (data) {
						var response = JSON.stringify(data);
						console.log("detected face", data[0].faceId);
						$("#responseTextArea").text(response);
						if (response == "[]") {
							error_result.innerHTML = "No Faces Detected, Try Again";
						} else {
							error_result.innerHTML = "";
							//addPersonFace(blobData);
							detectFunction(blobData, data[0].faceId );
						}
					})
					.fail(function (err) {
						$("#responseTextArea").append("\n\n---------FACE DETECTED SUCCESSFULLY----------\n\n");
						$("#responseTextArea").text(JSON.stringify(err));
						error_result.innerHTML = "Error Detecting faces";
					})
				});

		}
	}
	function IdentifyFace(blobData, faceID) {
		var urlData = "https://southcentralus.api.cognitive.microsoft.com/face/v1.0/identify";
		var _data = '{"personGroupId":"grupo-monge", "faceIds":[ "' + faceID+'" ], "maxNumOfCandidatesReturned":1, "confidenceThreshold": 0.5  }';
		console.log("image to detect", urlData, " Detected Face ID ", faceID, " DATA ", _data);

		if (!faceID) {
			displayErrorMessage( "Face ID NULL",null );
			return;
		 }

		$.post({
			url: urlData,
			contentType: "application/json",
			headers: {
				'Ocp-Apim-Subscription-Key': subscriptionKey
			},
			processData: false,
			//data: blobData
			data: _data,
		}).done(function (data) {
			$("#responseTextArea").append("\n\n---------PERSON FACE IDENTIFICATION SUCCESSFULL----------\n\n");
			$("#responseTextArea").append(JSON.stringify(data));
			$("#responseTextArea").append("\n\n-------------------\n\n");
			getIdentifyUser( data[0].candidates[0] );
		}).fail(function (err) {
			$("#responseTextArea").append("\n\n---------ADD PERSON FACE ERROR---------\n\n");
			$("#responseTextArea").append(JSON.stringify(err));
		});
	}
	function getIdentifyUser(candidate) {
		var candidateID = candidate.personId;
		console.log(candidate.personId);
		$("#text_results").html("Recognized User ID: " + candidateID);

		var urlData = "https://southcentralus.api.cognitive.microsoft.com/face/v1.0/persongroups/grupo-monge/persons/" + candidateID;

		$.get({
			url: urlData,
			contentType: "application/json",
			headers: {
				'Ocp-Apim-Subscription-Key': subscriptionKey
			},
			processData: false,
			//data: blobData
			//data: _data,
		}).done(function (data) {
			$("#responseTextArea").append("\n\n---------PERSON GET FACE SUCCESSFULL----------\n\n");
			$("#responseTextArea").append(JSON.stringify(data));
			$("#responseTextArea").append("\n\n-------------------\n\n");

			$("#text_results").html("Recognized User ID: " + data.personId + " <br/><br/>Email: " + data.name +" <br/><br/>Password: "+data.userData);

			$("#email_input").val(data.name);
			$("#password_input").val(data.userData);
			$("#submit_btn").trigger('click');

		}).fail(function (err) {
			$("#responseTextArea").append("\n\n---------ADD PERSON FACE ERROR---------\n\n");
			$("#responseTextArea").append(JSON.stringify(err));
		});
	}
</script>


@section Scripts {
	@await Html.PartialAsync("_ValidationScriptsPartial")
}

MongeTestCatalogs/Pages/Account/ResetPasswordConfirmation.cshtml
@page
@model ResetPasswordConfirmationModel
@{
    ViewData["Title"] = "Reset password confirmation";
}

<h2>@ViewData["Title"]</h2>
<p>
    Your password has been reset. Please <a asp-page="./Login">click here to log in</a>.
</p>